### ISSUE TITLE
RuntimeError: shape '[32, 10]' is invalid for input of size 160

### ISSUE THREAD

**Issue by Kirito0816** [gsp-27/pytorch_Squeezenet#4]
Sorry to disturb. I tried to run squeezenet using pytorch on GPU. And I got this error at the end of Epoch 1.
Train Epoch: 1 [48992/50000 (98%)]	Loss: 1.618558
Train Epoch: 1 [49312/50000 (99%)]	Loss: 1.442842
Train Epoch: 1 [49632/50000 (99%)]	Loss: 1.601359
Train Epoch: 1 [49952/50000 (100%)]	Loss: 1.511631
Traceback (most recent call last):
  File "main.py", line 228, in <module>
    train_acc.append(train(i))
  File "main.py", line 131, in train
    scores = scores.view(args.batch_size, args.num_classes)
RuntimeError: shape '[32, 10]' is invalid for input of size 160
Thank you for any suggestion.

**Comment by Kirito0816** [comment]
use "scores = scores.view(-1, args.num_classes)" to replace  "scores = scores.view(args.batch_size, args.num_classes)" could solve the error.
